version: '3'
services:
    fibonacci-server:
        build:
            context: ./fibonacci-server
            dockerfile: Dockerfile.dev
        environment: 
            TZ: Asia/Tokyo
        volumes:
            - ./fibonacci-server/code:/code
        ports:
            - 8080:8080
        env_file:
            - fibonacci-server/.env
        tty: true